### ISSUE TITLE
Unable to `connect`

### ISSUE THREAD

**Issue by imranolas** [contentstack/contentstack-cli#1]
Running the command `contentstack connect` with valid credentials terminates with the following message:

`Callback must be a function`

**Comment by iyerrama29** [comment]
Hi Ranolas,

Can you please elaborate a bit more on how to reproduce this issue?

The following info might help us debug this issue better:
- node version
- cli version
- way it was installed

**Comment by imranolas** [comment]
Node: v10.5.0
CLI: v3.0.4

Installed via npm as documented. `$ npm install -g contentstack-cli`

Running the following command should generate the same error for you 🤞 
https://github.com/contentstack/contentstack-cli#connect

**Comment by iyerrama29** [comment]
Hi Ranolas,

Thanks for informing us of the issue. We were able to reproduce the above issue on node v10.x.x

Ideally, we recommend that you use v8.11.4 and below to run the module.

Our team will look into it and keep you posted.

Thanks!

**Comment by iyerrama29** [comment]
Closing this issue - as it has been fixed in v3.0.5
